name:                seminal-haskell
version:             0.0.1
github:              "Arthi-chaud/seminal-haskell"
license:             BSD3
author:              "Arthur Jamet"
maintainer:          "aj530@kent.ac.uk"
copyright:           "2023 Arthur Jamet"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Enhance Type Error Messages

dependencies:
- base >= 4.7 && < 5

default-extensions:
- TupleSections
- PackageImports

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - directory
  - ghc-lib
  - exceptions
  - time
  - ghc-paths
  - utility-ht
  - bytestring
  - text
  exposed-modules:
  - Seminal
  - Seminal.Options
  - Seminal.Change
  ## For testing purposes, ugh
  - Seminal.Compiler.Runner
  - Seminal.Compiler.TypeChecker

executables:
  seminal-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seminal-haskell
    - timeit
    - optparse-applicative

tests:
  seminal-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - filepath
    - text
    - HUnit
    - test-framework
    - test-framework-hunit
    - seminal-haskell
