name: Build
on:
  push:
    branches:
      - '*'

jobs:
  Build:
    name: Build (LTS ${{ matrix.lts-version }})
    strategy:
      fail-fast: false
      matrix:
        lts-version: [
          20.26,
          20.24,
          20.23,
          20.21,
          20.12,
          20.11
        ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Compile Project
        run: stack --resolver lts-${{ matrix.lts-version }} build
      # This is to check if the project has been compiled with the correct version of ghc-lib.
      # For example, if there is a mismatch, we would get something like "Unknown Constructor: Char" 
      - name: Check Basic Suggestion
        run: stack --resolver lts-${{ matrix.lts-version }} run test/assets/invalid/expect-char.hs