name: Build
on:
  push:
    branches:
      - '*'

jobs:
  Build:
    name: Build (LTS ${{ matrix.lts-version }})
    strategy:
      fail-fast: false
      matrix:
        lts-version: [
          20.26,
          20.24,
          20.23,
          20.21,
          20.12,
          20.11,
          19.33
          # 18.8,
          # 18.6,
          # 18.28,
          # 17.2,
          # 16.31,
          # 16.11,
          # 15.3,
          # 14.27,
          # 13.19,
          # 13.11,
          # 12.26,
          # 12.14
        ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Generate stack file
        run: bash gen-stack.sh ${{ matrix.lts-version }}
      - name: Compile Project
        run: stack build --stack-yaml stack-lts-${{ matrix.lts-version }}.yaml
      # This is to check if the project has been compiled with the correct version of ghc-lib.
      # For example, if there is a mismatch, we would get something like "Unknown Constructor: Char" 
      - name: Check Basic Suggestion
        run: stack run --stack-yaml stack-lts-${{ matrix.lts-version }}.yaml test/assets/invalid/expect-char.hs