name: Build
on:
  push:
    branches:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Compile Project
        run: stack build
