name: Unit tests
on:
  push:
    branches:
      - '*'
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install stack
        run: curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Run unit tests
        run: stack test
