name: Unit tests
on:
  push:
    branches:
      - '*'
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Run unit tests
        run: stack test
